source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "~> 3.1"

gem "rails", ">= 6.0"
gem "puma", "~> 5.0"
gem "sqlite3", "~> 1.4"

# Use the parent gem from local path
gem "tailwindcss-rb", path: "../.."

group :development, :test do
  gem "rspec-rails"
  gem "debug"
end